export const DEFAULT = {
    blockWebsites: [
        { url: "facebook.com", active: true },
        { url: "youtube.com", active: true },
        { url: "twitter.com", active: true },
        { url: "reddit.com", active: true },
        { url: "pinterest.com", active: true },
        { url: "vimeo.com", active: true },
        { url: "tumblr.com", active: true },
        { url: "instagram.com", active: true },
        { url: "tiktok.com", active: true },
        { url: "quora.com", active: true },
        { url: "yahoo.com", active: true },
        { url: "netflix.com", active: true },
    ],
    // timeTracker: [],
    // elapsed: 0,
    pausedActivated: {
        timestamp: 0,
        pauseAmount: 5,
        resetAmount: 30,
    },
    pauseAmount: 5,
    resetAmount: 30,
    activated: true,
}
